[model]
enabled_extensions = [
    'rv_i',
    'rv_m',
    'rv_a',
    'rv_c',
    'rv_f',
    'rv_v',
    'rv_zicsr', 
    'rv_zifencei',
    'rv32_i',
    'rv32_c',
    'rv32_c_f',
    'rv_system',
]
