[package]
name = "online_drive"
version = "0.1.0"
edition = "2021"

[dependencies]
online_dpi = { path = "../online_dpi" }
svdpi = { workspace = true, features = ["sv2023"] }

[build-dependencies]
cmake = "0.1.50"

[features]
trace = ["online_dpi/trace"]
