name: Chisel and CIRCT Bump
on:
  schedule:
    # Run this job everyday at 5:30 AM UTC+8
    - cron:  '30 21 * * *'
  workflow_dispatch:

jobs:
  bump-deps:
    name: "Bump Chisel and CIRCT"
    if: ${{ !cancelled() }}
    runs-on: [self-hosted, linux, nixos]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - name: Bump Chisel
        run: |
          cd nix/t1/dependencies
          nix run '.#nvfetcher' -- -f '^chisel$'
      - name: Bump circt
        run: |
          oldFirtool="$(nix build '.#circt' --no-link --print-out-paths)/bin/firtool"
          nix flake update nixpkgs-for-circt
          newFirtool="$(nix build '.#circt' --no-link --print-out-paths)/bin/firtool"
          diff_bin="$(nix build '.#diffutils' --no-link --print-out-paths)/bin/diff"
          if "$diff_bin" -u <($oldFirtool --version) <($newFirtool --version); then
            # if unchanged
            git restore flake.lock
          fi
      - name: Bump all mill deps
        run: |
          ./dependencies/bump-ivy
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.T1_PR_PAT }}
        run: |
          git config user.name Avimitin
          git config user.email dev@avimit.in

          currentDate=$(date +%F)
          branch="dependencies-bumping-$currentDate"
          git checkout -b "$branch"

          git add 'dependencies'
          git add 'flake.lock'
          fileUnchanged() {
            git diff --quiet --exit-code "$@"
          }

          if ! git diff --quiet --cached --exit-code; then
            updatedFiles=$(git diff --cached --name-only)
            echo "File changed"
            git commit -m "[deps] Bump T1 dependencies"
            git push origin "$branch" --force-with-lease
            nix run '.#gh' -- \
              pr create --title "Bump T1 dependencies" --body "Updated: $updatedFiles"
          fi
